### ISSUE TITLE
Add blur for footer

### ISSUE THREAD

**Issue by seanzhang98** [KyleGospo/Steam-Deck-Themes#1]
Hi, 

Love your work! It is possible to add blur to the footer as well?

Thanks

**Comment by KyleGospo** [comment]
Unfortunately due to how SteamOS lays out the footer there's no good way to blur it. I can make it transparent but all that's behind it is black. If I fix that, any scrolling menu will need additional margins so that the footer isn't covering part of the scrollable content, for which there are too many elements to realistically fix.
